### ISSUE TITLE
How to add token to all response header?

### ISSUE THREAD

**Issue by nelsonic** [atomantic/hapi-auth-header#1]
@atomantic looks good.
How do you ensure that the `Authorization` header is always set for the **reply** so the client knows which token to send back?

**Comment by atomantic** [comment]
If you are replying from the Authorization token granting API, you can just use the reply interface in that API handler:

```
reply(body).header('Authorization', 'Bearer '+token);
```

or if for some reason you need to send it back the token they sent you... (not sure why this would be needed):

```
// return the same authorization header that they sent us:
reply(body).header('Authorization', request.headers.authorization);
```

This is just a Hapi.js thing:

http://hapijs.com/api#reply-interface

**Comment by nelsonic** [comment]
Thanks for your prompt reply! :-)

Can the header be set in the plugin or **validateFunc** to avoid having to add the 

``` js
reply(body).header('Authorization', 'Bearer '+token);
```

to _every_ handler?

My understanding is that if we don't send the Auth header back to the client on each reply the client will not know they need to send it _back_ in subsequent requests... is this incorrect?

**Comment by atomantic** [comment]
In general, I'd say that your API spec should declare that the API needs to be called with the authorization header and whatever token standard you are using.

Your API should only have to send the token to the client once (via whatever token granting API you expose). Thereafter, the consumer of the API should have the token in memory/cache and know that your API requires that to be added to the header.

However, if you are in a bind with whatever architecture you have to support, you could reply with the header on every request using one of the Hapi.js Request Lifecycle functions: http://hapijs.com/api#request-lifecycle

For example:

```
server.ext('onPreResponse', function (request, reply) {
     return reply().header('Authorization', request.app.authtoken);
});
```

**Comment by nelsonic** [comment]
Thanks @atomantic :+1:
